apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: awms-guacamole
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: awms-guacamole
subjects:
- kind: ServiceAccount
  name: awms-guacamole-operator
  namespace: ${awms_guacamole_namespace}