apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: awms-guacamole
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "patch", "create", "delete"]

- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "patch", "create", "delete"]