apiVersion: xlscsde.nhs.uk/v1
kind: SecretsDistribution
metadata:
  name: guacamole
  annotations:
    xlscsde.nhs.uk/secretUsage: "Guacamole passwords"
spec:
  name: guacamole
  secrets:
  - from: GuacDbPassword
    to: db-password