apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: operator-config
    files:
      - values.yaml=config.yaml
generatorOptions:
  disableNameSuffixHash: true
resources:
- guacamole