name: Docker build and push

on:
  workflow_dispatch:
  push:
    branches:
    - 'main'

jobs:
  buildandpush:
    uses: lsc-sde/lsc-sde/.github/workflows/docker-release.yaml@main
    with:
      imageName: awms-guacamole-operator
      directory: products/sde/analytics-workspace-management/awms-guacamole-operator
      platforms: '["amd64"]'
      yamlPath: awms_guacamole
    secrets: inherit
  
  helm_package:
    uses: lsc-sde/lsc-sde/.github/workflows/helm-package.yaml@main
    needs: 
    - buildandpush
    with:
      symver: ${{ needs.buildandpush.outputs.GitVersion_SemVer }}
      directory: products/sde/analytics-workspace-management/awms-guacamole-operator
      subdirectory: "/helm"
    secrets: inherit

  update-helm-yaml:
    uses: lsc-sde/lsc-sde/.github/workflows/update-yaml.yaml@main
    needs: 
    - buildandpush
    - helm_package
    with:
      repository: lsc-sde/iac-flux-lscsde
      path: "core/helm-config.yaml"
      yamlPath: ".components.awms_guacamole.chart_version"
      newValue: "${{ needs.buildandpush.outputs.GitVersion_SemVer }}"
    secrets: inherit

  update-flux-yaml:
    uses: lsc-sde/lsc-sde/.github/workflows/update-yaml.yaml@main
    needs: 
    - buildandpush
    - helm_package
    with:
      repository: lsc-sde/iac-flux-lscsde
      path: "core/flux-config.yaml"
      yamlPath: ".components.awms_guacamole.repository.branch"
      newValue: "release/${{ needs.buildandpush.outputs.GitVersion_SemVer }}"
    secrets: inherit
